---
title: 'Hands on Examples'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This repository contains materials for hands on examples for the Effective Visual Communication Webinar for the [ASCPT Pharmacometrics & Pharmacokinetcs (PMK) Community](https://www.ascpt.org/Member-Services/Member-Tools/Webinar-Resources).

For the assignment, **pick one** of the options below:

* **Option 1 (improve a graph):** [Capmatinib NSCLC MET mutations](Capmatinib_NSCLC_MET_mutations/)
* **Option 2 (create a graph):** [Missed doses due to COVID-19](Missed_Doses_Due_to_COVID/)
* **Option 3:** Bring your own example


# Assignment:

* **Step 1 (have a clear purpose):** Complete the Purpose Worksheet for the example you choose. Partially completed purpose worksheets are available for supplied examples. If you choose to bring your own example, a blank purpose worksheet is available here: [Purpose_Worksheet.docx](Purpose_Worksheet.docx)
* **Step 2 (show the data clearly):** Select what data to display, and how to display it, iterate through a few alternatives in quick sketches
* **Step 3 (make the message obvious):** Choose a graph or two from the previous step, and refine to make the message obvious

# How to submit your responses?

Please submit your examples ahead of Part 2 of the webinar for discussion/feedback using the [following webform](https://docs.google.com/forms/d/e/1FAIpQLScB3PMzu2shmkzWHO8wTZ9dNaMibRSGjLnZK4uWeUQ_sUJUBg/viewform). 

If you do not have a google drive login, or if you experience any issues with the [webform](https://docs.google.com/forms/d/e/1FAIpQLScB3PMzu2shmkzWHO8wTZ9dNaMibRSGjLnZK4uWeUQ_sUJUBg/viewform), please [email](mailto:graphics.principles@gmail.com) your submissions directly to us. 

# Any questions?

For any questions please reach out directly to the facilitators through [email](mailto:graphics.principles@gmail.com) or the [discussion board](https://github.com/GraphicsPrinciples/webinar/discussions). 


# References

* [Cheat sheet and tutorial](https://graphicsprinciples.github.io/)
* The purpose worksheet is inspired by the [big idea worksheet](https://drive.google.com/file/d/1WJDLkMVTxlDHyeGWzeKQmSiXdmlxQSAg/view) from the book:
Knaflic, Cole. Storytelling With Data: Let’s Practice! Wiley, © 2019. http://www.storytellingwithdata.com/

# More resources and references

Here are a list of other useful resources and related initiatives.

Graphical principles initiative:

* A [Rstudio Rviews webinar](https://resources.rstudio.com/webinars/effective-visualizations-for-data-driven-decisions) on graphics principles and visR, and [blog post](https://blog.rstudio.com/2020/04/16/effective-visualizations-for-credible-data-driven-decision-making/)
* R in Pharma 2020 talk on [EVC](https://graphicsprinciples.github.io/assets/EVC_Magnusson_RPharma2020.pdf), [slides](https://graphicsprinciples.github.io/assets/EVC_Magnusson_RPharma2020.pdf) and [video](https://www.youtube.com/watch?v=TNMC-Ota29g&list=PLMtxz1fUYA5DSpVzwR7bT37IZqCT4SH5a&index=4).
* The [xGx](https://opensource.nibr.com/xgx/) initiative from Novartis PMX.

Data visualization initiatives:

* PSI special interest group on [visualisation](https://www.psiweb.org/sigs-special-interest-groups/visualisation) (VIS SIG).
* The PSI VIS SIG [Wonderful Wednesdays](https://www.psiweb.org/sigs-special-interest-groups/visualisation/welcome-to-wonderful-wednesdays) webinar series, [datasets](https://github.com/VIS-SIG/Wonderful-Wednesdays) and [blog](https://vis-sig.github.io/blog/).
* The [CTSpedia](https://www.ctspedia.org/do/view/CTSpedia) initiative. 
* The STRengthening Analytical Thinking for Observational Studies [(STRATOS)](https://www.stratos-initiative.org/) visualisation [panel](https://www.stratos-initiative.org/node/61) 
* The [visR initiative](https://openpharma.github.com/visR).

Online resources:

* [Trees, maps and theorems](https://www.principiae.be/book/) by Jean-luc Doumont
* [Data visualization](https://socviz.co/) by Kieran Healy - includes R code with examples.
* [Fundamentals of data vizualisation](https://serialmentor.com/dataviz/) by Claus O. Wilke - also includes R code with examples.


